#runtime: aspnetcore
#env: flex
#service: micro
steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/bandlavenubabu/GCP.git']
 # args: ['cd','']
- name: 'gcr.io/cloud-builders/dotnet'
  args: [ 'publish', '-c', 'Release' ]
  dir: 'GCP/HelloWorld/'
#- name: 'gcr.io/$PROJECT_ID/gcloud'
#  args: ['info']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'app', 'deploy', '/bin/Release/netcoreapp2.1/publish/appdeploy.yaml' ]
  dir: 'GCP/HelloWorld/' 
#manual_scaling:
 # instances: 1
  
#resources:
#  cpu: 1
#  memory_gb: 0.5
#  disk_size_gb: 10
  
#env_variables:
  # The __ in My__Greeting will be translated to a : by ASP.NET.
#  My__Greeting: Hello world!
